### ISSUE TITLE
Objects with empty IDs

### ISSUE THREAD

**Issue by csuhta** [chevEldrid/pdh-json-updater#59]
The current pauper_commander.json includes some items with empty oracleID fields, example:

```
  {
    "py/object": "pdh_json_updater.json_card.JsonCard",
    "scryfallOracleId": "",
    "name": "Command Tower // Command Tower",
    "legality": "Legal"
  }
```

The point of this file is to sync it, so these entries are not useful. You could either omit reversible prints, or include both IDs somehow.

**Comment by chevEldrid** [comment]
Yeah when we came across them in the REX set wasn't sure how to proceed since those specific printings didn't have oracleIds and decided to proceed with these dummy values, but we're going to move to remove these as independent entries!

**Comment by chevEldrid** [comment]
Okay! Removed the cards with empty ids and currently implemented the behavior for reversible cards (or cards without an oracle id at the top level), use the oracle id on the front card face. Just waiting for [review](https://github.com/chevEldrid/pdh-json-updater/pull/60)!
